# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8525d7c64c32068b10d3800832823742"
name = "Build-Your-Box"
handle = "build-your-box-1"
application_url = "https://stops-weekend-honors-headline.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "greenchoice-flowers-subscriptions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_content"

[app_proxy]
url = "https://app.example.com/api/proxy"
subpath = "test"
prefix = "apps"

[auth]
redirect_urls = [
  "https://stops-weekend-honors-headline.trycloudflare.com/auth/callback",
  "https://stops-weekend-honors-headline.trycloudflare.com/auth/shopify/callback",
  "https://stops-weekend-honors-headline.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
